### PR TITLE
Fix #71: Deprecate `CsrfMiddleware` in favor of `CsrfTokenMiddleware`

### LINKED ISSUE #70: Rename `CsrfMiddlware` to `CsrfTokenMiddleware`
- Copy `CsrfMiddlware` to new class `CsrfTokenMiddleware`.
- Mark `CsrfMiddlware` as deprecated.

### PR DESCRIPTION
**Pull request by ev-gor**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌

Fix #70

### CODE REVIEW

**Comment by ev-gor** [comment]
I just copy/paste existing code, but I can add missing tests if needed

**Comment by samdark** [comment]
@ev-gor deprecated class could be excluded from testing.

**Comment by vjik** [comment]
> @ev-gor deprecated class could be excluded from testing.

Why? It's reduced code coverage. I suggest removing tests for deprecate classes at the time of their deletion.

**Comment by samdark** [comment]
Alright. @vjik suggestion makes sense.

**Comment by ev-gor** [comment]
OK, I added tests for the new class and left tests for the deprecated one but with prefix 'Deprecated' in their names to make it easier to remove them in the future.

**Review by vjik — APPROVED** [review]

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
